# Generated by Django 3.2.5 on 2021-12-26 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_body', models.CharField(max_length=1000)),
                ('blog_date', models.DateField()),
                ('blog_author', models.CharField(max_length=100)),
                ('blog_topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogApp.topic')),
            ],
        ),
    ]
