# Generated by Django 3.2.5 on 2021-12-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_auto_20211227_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
